server.port=8080

spring.application.name=dashboard_gk
spring.data.mongodb.uri=mongodb+srv://Gabriel2514:DqYycV2m1UqtYltJ@cluster0.0mxktmv.mongodb.net/
spring.data.mongodb.database=dashboard_project_db
spring.data.mongodb.auto-index-creation=true

# JWT
jwt.secret=QlqSmnTZ/gL+2dtNa/8GJW6n+cNFT6a+UBVGgLMoRf0=
jwt.expiration=20000
# jwt.expiration=3600000
